[env]
TERM = "xterm-256color"

[terminal.shell]
program = "zellij"

[window]
padding.x = 14
padding.y = 12
decorations = "None"
opacity = 0.98
startup_mode = "Windowed"

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 12.0

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = "Block"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true
